### ISSUE TITLE
Poor and misleading error message on trouble with config for central key generation

### ISSUE THREAD

**Issue by DDvO** [siemens/cmp-ra-component#3]
* When the configuration is missing signature credentials, the error message is <br>`could not validate enrolled certificate: null`
* When the configuration gives an unknown or invalid algorithm, e.g., `AES255` in PasswordContext, the error message is <br>`could not validate enrolled certificate: AES255`

**Comment by Akretsch** [comment]
- error message changed to "could not properly process certificate response" + more specific description of exception.  
- Exception backtrace is logged

**Comment by Akretsch** [comment]
fixed in e669853d4e16840d960c98dd0ed0df182a71d631

**Comment by DDvO** [comment]
Hmm, on missing `SignatureCredentials`, the new error  `downstream: could not properly process certificate response: java.lang.NullPointerException` is no more misleading, but still not to the point.
And as discussed, this should already be caught by the config parser of the LwCmpRa.

**Comment by DDvO** [comment]
For invalid alg, the output is now fine, e.g., `NoSuchAlgorithmException: SHA25500`

**Comment by DDvO** [comment]
Since improving the parser is not possible and this anyway would not help within the CmpRaComponent,
I suggest in the given case, e.g., `central key generation configuration is missing signature credentials`

**Comment by Akretsch** [comment]
fixed in 8f886d86ba9f82ad6a0764dc5b3df9ae79310644
